#pragma once

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DRIVE_CAN_OFFSET_CONTROL_RX 0U
#define DRIVE_CAN_OFFSET_STATUS_TX 1U
#define DRIVE_CAN_OFFSET_MODE_TX 2U
#define DRIVE_CAN_OFFSET_MEASUREMENT_TX 3U
#define DRIVE_CAN_OFFSET_COMMAND_RX 4U
#define DRIVE_CAN_OFFSET_RESPONSE_TX 5U

#define DRIVE_STATUS_SIGNATURE 0xD7U

static inline uint32_t drive_protocol_make_id(uint32_t base_id, uint32_t offset)
{
    return base_id + offset;
}

typedef enum {
    DRIVE_COMMAND_CALIBRATE = 0x01,
    DRIVE_COMMAND_CONFIG_GET = 0x02,
    DRIVE_COMMAND_CONFIG_SET = 0x03,
    DRIVE_COMMAND_CLEAR_FAULT = 0x04,
} drive_command_t;

typedef enum {
    DRIVE_RESPONSE_ACK = 0x80,
    DRIVE_RESPONSE_IN_PROGRESS = 0x81,
    DRIVE_RESPONSE_OK = 0x82,
    DRIVE_RESPONSE_ERROR = 0xFF,
} drive_response_t;

typedef enum {
    DRIVE_CONFIG_KEY_CAN_BASE_ID = 0x01,
    DRIVE_CONFIG_KEY_CURRENT_ZERO_CHANNEL_VOLTS = 0x02,
    DRIVE_CONFIG_KEY_BUS_VOLTAGE_OFFSET_VOLTS = 0x03,
    DRIVE_CONFIG_KEY_CONTROL_MODE = 0x04,
    DRIVE_CONFIG_KEY_CURRENT_LIMIT_AMPS = 0x05,
    DRIVE_CONFIG_KEY_CURRENT_KI_UP = 0x06,
    DRIVE_CONFIG_KEY_CURRENT_KI_DOWN = 0x07,
    DRIVE_CONFIG_KEY_CURRENT_OVERCURRENT_MARGIN_AMPS = 0x08,
    DRIVE_CONFIG_KEY_CURRENT_OVERCURRENT_MARGIN_PERCENT = 0x09,
    DRIVE_CONFIG_KEY_CURRENT_ERROR_CLAMP_AMPS = 0x0A,
    DRIVE_CONFIG_KEY_PWM_RAMP_UP_PER_SEC = 0x0B,
    DRIVE_CONFIG_KEY_PWM_ERROR_CLAMP = 0x0C,
    DRIVE_CONFIG_KEY_PWM_BACKOFF_PER_SEC = 0x0D,
} drive_config_key_t;

typedef enum {
    DRIVE_CONTROL_MODE_PWM = 0,
    DRIVE_CONTROL_MODE_CURRENT = 1,
    DRIVE_CONTROL_MODE_OTHER = 2,
} drive_control_mode_t;

typedef enum {
    DRIVE_CONTROLLER_MODE_RUNNING = 0,
    DRIVE_CONTROLLER_MODE_DISABLED = 1,
    DRIVE_CONTROLLER_MODE_CALIBRATING = 2,
    DRIVE_CONTROLLER_MODE_FAULT_LOCKOUT = 3,
} drive_controller_mode_t;

typedef enum {
    DRIVE_COMMAND_ERROR_INVALID_PAYLOAD = 1,
    DRIVE_COMMAND_ERROR_BUSY = 2,
    DRIVE_COMMAND_ERROR_UNSUPPORTED_KEY = 3,
    DRIVE_COMMAND_ERROR_STORAGE = 4,
    DRIVE_COMMAND_ERROR_INTERNAL = 5,
} drive_command_error_t;

#ifdef __cplusplus
}
#endif